### PR TITLE
Do not use myst cli

### PR DESCRIPTION
**Pull request by fwkoch**

### CODE REVIEW

**Review by rowanc1 — APPROVED** [review]

**Comment by rowanc1** [comment]
We probably need to tag something to release?

**Comment by fwkoch** [comment]
Yeah. I can copy in the actions that do that from `actions`. Or we could also move this into `actions`...

**Comment by rowanc1** [comment]
I feel like we start to deprecate this repo when actions is better setup, and we can init from the CLI.

**Comment by fwkoch** [comment]
Cool, yeah - I'm just going to merge and manually tag. This doesn't really have the complexity to require the release actions...

**Pull request merged**
